import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "../components/header"
import Footer from "@/components/footer";
import { useEffect, useState } from "react";

export default function Blog() {
    const [data, setData] = useState([])
    const [isLoading, setLoading] = useState(false)

    useEffect(() => {
      setLoading(true)
      fetch('/api/notionblog')
        .then((res) => res.json())
        .then((data) => {
          setData(data)
          setLoading(false)
        })
    }, [])

    if (isLoading) return <p>Loading...</p>
    if (!data) return <p>No profile data</p>


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/web_logo.png" />
      </Head>
      <Header pageName={"reachme"}></Header>

      <main className="container mx-auto w-3/4 md:w-1/2">
        {data.map((value) => {
          return (
          <ul key={value.id}>
            <li>{value.title}</li>
            <li dangerouslySetInnerHTML={{__html : value.body}}></li>
          </ul>
          )
        })}
      </main>
      <Footer/>
    </>
  );
}
