// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import Head from "next/head";
import Header from "../components/header"
import Footer from "@/components/footer";
import { useEffect, useState } from "react";
import { NotionRenderer } from 'react-notion-x'
// core styles shared by all of react-notion-x (required)
import { Code } from 'react-notion-x/build/third-party/code'
import { Collection } from 'react-notion-x/build/third-party/collection'
import { Equation } from 'react-notion-x/build/third-party/equation'
import { Modal } from 'react-notion-x/build/third-party/modal'
import { Pdf } from 'react-notion-x/build/third-party/pdf'
import 'react-notion-x/src/styles.css'

// used for code syntax highlighting (optional)
import 'prismjs/themes/prism-tomorrow.css'

// used for rendering equations (optional)
import 'katex/dist/katex.min.css'
export default function Notionx() {
    const [data, setData] = useState(null)
    const [isLoading, setLoading] = useState(false)

    useEffect(() => {
      setLoading(true)
      fetch('/api/notionx')
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        setData(data)
        setLoading(false)
      })
    }, [])

    if (isLoading) return <p>Loading...</p>
    if (!data) return <p>No profile data</p>

    return (
      <>
      <Head>
        <title>{process.env.NEXT_PUBLIC} About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/web_logo.png" />
      </Head>
      <Header pageName={"reachme"}></Header>

      
      <main className="container mx-auto w-3/4 md:w-1/2">
        <NotionRenderer 
          recordMap={data} 
          fullPage={true} 
          pageHeader={<>Hello</>} 
          header={<>Haiii</>} 
          disableHeader={true}
          darkMode={true} 
          className="dark:bg-neutral-900"
          components={{
            Code,
            Collection,
            Equation,
            Modal,
            Pdf
          }} 
          showTableOfContents={true} />
      </main>
      <Footer/>
    </>
      )
  }
  