import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "../components/header"
import Footer from "@/components/footer";

export default function Project() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/web_logo.png" />
      </Head>
      <Header pageName={"project"}></Header>

      <main className="container mx-auto w-3/4 md:w-2/3 mb-auto">
        {/* <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 ">
            <div className="w-full px-4 flex flex-wrap justify-center">
                <div className="mb-12 p-4">
                    <div className="rounded-md shadow-md overflow-hidden">
                        <img src="720_image.jpg" />
                    </div>
                    <h3 className="font-semibold text-dark text-xl mt-5 mb-3">Irham Kentu Landing Page</h3>
                    <p className="font-medium text-base text-secondary">Lorem Ipsum Dolo Sit amet</p>
                </div>
            </div>
            <div className="w-full px-4 flex flex-wrap justify-center">
                <div className="mb-12 p-4">
                    <div className="rounded-md shadow-md overflow-hidden">
                        <img src="720_image.jpg" />
                    </div>
                    <h3 className="font-semibold text-dark text-xl mt-5 mb-3">Irham Kentu Landing Page</h3>
                    <p className="font-medium text-base text-secondary">Lorem Ipsum Dolo Sit amet</p>
                </div>
            </div>
        </div> */}

<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
    <div className="w-full flex flex-wrap justify-center border-2">
        <div className="mb-12">
            <div className="shadow-md overflow-hidden">
                <img src="https://www.rbw.it/en/wp-content/uploads/sites/4/2016/10/1280x720-text.png" />
            </div>
            <div className="container p-4">
                <h3 className="font-semibold text-dark text-xl">Irham Kentu Landing Page</h3>
                <p className="text-sm text-secondary">Lorem Ipsum Dolo Sit amet</p>
            </div>
        </div>
    </div>
    <div className="w-full flex flex-wrap justify-center border-2">
        <div className="mb-12">
            <div className="shadow-md overflow-hidden">
                <img src="https://www.rbw.it/en/wp-content/uploads/sites/4/2016/10/1280x720-text.png" />
            </div>
            <div className="container p-4">
                <h3 className="font-semibold text-dark text-xl">Irham Kentu Landing Page</h3>
                <p className="text-sm text-secondary">Lorem Ipsum Dolo Sit amet</p>
            </div>
        </div>
    </div>
    <div className="w-full flex flex-wrap justify-center border-2">
        <div className="mb-12">
            <div className="shadow-md overflow-hidden">
                <img src="https://www.rbw.it/en/wp-content/uploads/sites/4/2016/10/1280x720-text.png" />
            </div>
            <div className="container p-4">
                <h3 className="font-semibold text-dark text-xl">Irham Kentu Landing Page</h3>
                <p className="text-sm text-secondary">Lorem Ipsum Dolo Sit amet</p>
            </div>
        </div>
    </div>
    <div className="w-full flex flex-wrap justify-center border-2">
        <div className="mb-12">
            <div className="shadow-md overflow-hidden">
                <img src="https://www.rbw.it/en/wp-content/uploads/sites/4/2016/10/1280x720-text.png" />
            </div>
            <div className="container p-4">
                <h3 className="font-semibold text-dark text-xl">Irham Kentu Landing Page</h3>
                <p className="text-sm text-secondary">Lorem Ipsum Dolo Sit amet</p>
            </div>
        </div>
    </div>
</div>

      </main>
      <Footer/>
    </>
  );
}
