import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "../components/header"
import Footer from "@/components/footer";

export default function Reachme() {
  return (
    <>
      <Head>
        <title>Reach Me!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/web_logo.png" />
      </Head>
      <Header pageName={"reachme"}></Header>

      <main className="container mx-auto w-3/4 md:w-1/2">
        <p>Linkedin : <a target="_blank" class="hover:text-sky-500 hover:border-b-2 hover:border-sky-500" href="https://linkedin.com/in/patarshn">Patar Martua Doli Siahaan</a></p>
        <p>Instagram : <a target="_blank" class="hover:text-sky-500 hover:border-b-2 hover:border-sky-500" href="https://instagram.com/patarshn">patarshn</a></p>
        <p>Email : <a target="_blank" class="hover:text-sky-500 hover:border-b-2 hover:border-sky-500" href="mailto:patarmds@gmail.com">patarmds@gmail.com</a></p>
      </main>
      <Footer/>
    </>
  );
}
